routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('groups', 'GroupController');

Route::resource('sorts', 'SortController');

Route::resource('invitations', 'InvitationController');

Route::post('accept-invitation', 'InvitationController@accept')->name('accept-invitation');

Route::post('search-users', 'UserController@search')->name('search-users');

Route::post('get-sorts', 'SortController@getSorts')->name('get-sorts');

Route::post('/sorts/sort', 'SortController@sort')->name('/sorts/sort');

Route::post('search-users-edit', 'UserController@usersToGroup')->name('search-users-edit');

Route::post('invitations/invite', 'InvitationController@invite')->name('inivite');

Route::post('invitations/uninvite', 'InvitationController@uninvite')->name('uninvite');

Route::post('groups/delete-member', 'GroupController@deleteMember')->name('delete-member');




/**
 * Redireciona todas as requisições em URL's não especificadas
 * para a página principal.
 */

Route::any('{all}', function () {
    return redirect("/");
})->where('all', '.*');

app/Sort.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sort extends Model
{
    protected $fillable = [
        'id',
        'idGroup',
        'event',
        'sorted'
    ];

    protected $table = 'sorts';

    public function group(){

        return $this->belongsTo('App\Group', 'idGroup');        
    }
}

app/Http/Controllers/SortController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Group;
use Auth;
use App\Sort;
use App\SortResult;
use App\GroupMember;
use Log;


class SortController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = Group::where('idOwner',Auth::user()->id)->get();
        return view('sort.index',compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $groups = Group::where('idOwner', Auth::user()->id)->get();
        return view('sort.create',compact('groups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $sort = new Sort();
        $sort->idGroup = $request->sortGroup;
        $sort->event = $request->sortEvent;
        $sort->sorted = 0;
        $sort->save();

        return back()->with('success','Sorteio cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getSorts(Request $request)
    {
        $sorts = Sort::where('idGroup',$request->idGroup)->get();
        return response()->json(['sorts'=>$sorts]); 
    }

    public function sort(Request $request){
        
        
        $sort = Sort::find($request->idSort);
        $members = GroupMember::where('idGroup',$sort->idGroup)->get();
        if($members->count() < 2){
            return response()->json(['mensagem'=>'Numero de participantes insuficiente para o sorteio.'],404);
        }
        
        if($request->sorted){
            $resultRemoveSort = $this->removeSortResults($request->idSort);
            if($resultRemoveSort){
                $resultSort = $this->doSort($request->idSort);
            }
            else{
                return response()->json(['mensagem'=>'Erro ao resortear o amigo secreto.'],500);    
            }    
        }
        else{
            $resultSort = $this->doSort($request->idSort);
        }

        if($resultSort){
            $sort->sorted = 1;
            $sort->save();
            return response()->json(['mensagem'=>'Amigo secreto sorteado com sucesso! Veja o seu amigo na tela inicial.']);
        
        }
        else{
            return response()->json(['mensagem'=>'Erro ao sortear o amigo secreto.'],500);
        }
    }

    private function doSort($idSort){

        $sort = Sort::find($idSort);
        $members = GroupMember::where('idGroup',$sort->idGroup)->get();
        if($members){
            $arrMembers = $members->toArray();
            $arrSortResults = [];
            
            foreach($arrMembers as $member){
                $friend = $members->where('idMember','<>',$member['idMember'])->random();
                $sortResult = new SortResult();
                $sortResult->idFirstFriend = $member['idMember'];
                $sortResult->idSecondFriend = $friend->idMember;
                $sortResult->idSort = $idSort;

                $arrSortResults[] = $sortResult;

                $members = $members->where('idMember','<>',$friend->idMember);    

            }

            try{
                foreach($arrSortResults as $sortResult){
                    $sortResult->save();
                }
                return true;
            }
            catch(\Exception $e){
                Log::error('Erro ao sortear o amigo secreto: ',['exception'=>$e->getMessage()]);
                return false;
            }
        }    
    }

    private function removeSortResults($idSort){
        try{
            SortResult::where('idSort',$idSort)->delete();
            return true;
        }
        catch(\Exception $e){
            Log::error('Erro ao resortear o amigo secreto: ',['exception'=>$e->getMessage()]);
            return false;
        }    
    }
}

resources/views/sort/create.blade.php
@extends('layouts.base')

@section('content')

    
    <div class="title-group col-md-12">
        <h2>Cadastrar Sorteio</h2>
    </div>
    @if(isset($groups) && $groups->isNotEmpty())
    <div class="col-md-12 col-xs-12 form-center">   
        <form action="{{route('sorts.store')}}" method="POST">
            @csrf
            <div class="row">
                    <div class="form-group col-xs-6 col-md-6">
                            <label for="searchFor">Grupo</label>
                            <select name="sortGroup" class="form-control" id="searchFor">
                                @foreach($groups as $group)
                                <option value="{{$group->id}}">{{$group->name}}</option>
                                @endforeach
                            </select>
                    </div>
                    
                <div class="form-group col-md-6">
                        <label for="sortEvent">Evento</label>
                        <input type="text" name="sortEvent" class="form-control" id="sortEvent" placeholder="Natal,Confraternização,etc...">        
                </div>
            </div>       
            <button type="submit" class="btn btn-primary btn-create-group">Cadastrar</button>
        </form>
    </div>
    @else
    <div class="well text-center center col-md-12 col-xs-12">
            <h3>Nenhum Grupo Cadastrado, crie um grupo para criar um sorteio!</h3>
    </div>
    @endif

@endsection

resources/views/sort/index.blade.php
@extends('layouts.base')

@section('content')

    <div class="title-group col-md-12">
        <h2>Sorteios</h2>
    </div>
    @if(isset($groups) && $groups->isNotEmpty())
    <div class="col-md-12 col-xs-12 form-center">   
                
                <div class="col-xs-12 col-md-12">
                        <label for="searchFor">Grupo</label>
                        <select onchange="getSorts(this)" class="form-control" id="searchFor">
                            @foreach($groups as $group)
                            <option value="{{$group->id}}">{{$group->name}}</option>
                            @endforeach                            
                        </select>
                </div>
                
                <div id="div-table-sorts">
                    
                </div>        
                <div class="col-md-12">
                        <a href="{{route('sorts.create')}}">
                            <i class="icon-group-new fas fa-plus-circle"></i>
                            <p class="p-group">Criar Sorteio</p>
                        </a>       
                </div>
        </div>
        @else
        <div class="well text-center center col-md-12 col-xs-12">
                <h3>Nenhum Grupo Cadastrado, crie um grupo, depois crie um sorteio!</h3>
        </div> 
        @endif


@endsection