routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('groups', 'GroupController');

Route::resource('sorts', 'SortController');

Route::resource('invitations', 'InvitationController');

Route::post('accept-invitation', 'InvitationController@accept')->name('accept-invitation');

Route::post('search-users', 'UserController@search')->name('search-users');

Route::post('get-sorts', 'SortController@getSorts')->name('get-sorts');

Route::post('/sorts/sort', 'SortController@sort')->name('/sorts/sort');

Route::post('search-users-edit', 'UserController@usersToGroup')->name('search-users-edit');

Route::post('invitations/invite', 'InvitationController@invite')->name('inivite');

Route::post('invitations/uninvite', 'InvitationController@uninvite')->name('uninvite');

Route::post('groups/delete-member', 'GroupController@deleteMember')->name('delete-member');




/**
 * Redireciona todas as requisições em URL's não especificadas
 * para a página principal.
 */

Route::any('{all}', function () {
    return redirect("/");
})->where('all', '.*');

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $fillable = [
        'id',
        'name',
        'idOwner'
    ];

    protected $table = 'groups';
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Invitation;
use App\Group;
use App\GroupMember;
use Auth;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = Group::where('idOwner',Auth::user()->id)->get();
        return view('group.index', compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('group.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $group = new Group();
        $group->name = $request->name;
        $group->idOwner = Auth::user()->id;
        $group->save();

        $member = new GroupMember();
        $member->idMember = Auth::user()->id;
        $member->idGroup = $group->id;
        $member->save();
        
        if(!empty($request->users)){
            foreach($request->users as $idUser){
                $invite = new Invitation();
                $invite->idGuest = $idUser;
                $invite->idGroup = $group->id;
                $invite->save();
                
            }
        }

        return back()->with('success','Grupo cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $group = Group::find($id);
        return view('group.show',compact('group'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $group = Group::find($id);
        if($group){
            $group->name = $request->name;
            $group->save();

            return response()->json(['mensagem'=>'Grupo alterado com sucesso!']);
        }

        return response()->json(['mensagem' => 'Grupo não encontrado!'],404);        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        $group = Group::find($id);
        if($group){
            Group::where('id',$id)->delete();
            return response()->json(["mensagem"=>"Grupo deletado com sucesso!"]);            
        }
        
        return response()->json(["mensagem"=>"Grupo não encontrado!"],404);        
        
    }

    public function deleteMember(Request $request)
    {
        $member = GroupMember::where('idMember',$request->idUser)
                               ->where('idGroup',$request->idGroup)
                               ->delete();

        return response()->json(['mensagem'=>'Usuário retirado do grupo!']);
    }
}

resources/views/group/create.blade.php
@extends('layouts.base')

@section('content')

    
    <div class="title-group col-md-12">
        <h2>Cadastrar Grupo</h2>
    </div>
    <div class="col-md-12 col-xs-12 form-center">   
        <form action="{{route('groups.store')}}" method="POST">
            @csrf
            <div class="form-group col-xs-12 col-md-12">
                <label for="groupName">Nome</label>
                <input name="name" type="text" class="form-control" id="groupName" aria-describedby="emailHelp" placeholder="Digite o nome do grupo">
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="searchFor">Pesquisar por</label>
                    <select class="form-control" id="searchFor">
                        <option value="email">E-mail</option>
                        <option value="nome">Nome</option>
                    </select>   
                </div>
                <div class="form-group col-md-6">
                        <label for="inviteSomeone">Convidar Participantes</label>
                        <input id="searchUser" type="text" class="form-control" id="inviteSomeone" placeholder="Pesquisar...">
                            
                </div>
                <div class="form-group col-md-2">
                    <label for="btn-search"></label>
                    <button type="button" id="btn-search" class="btn form-control" onclick="searchUsers()">Buscar</button>
                </div>
            </div>
            <div>
            <div>
                <table class="table table-striped">
                        <thead>
                            <tr>
                            <th scope="col">Nome</th>
                            <th scope="col">E-mail</th>
                            <th scope="col">Convidar</th>
                            </tr>
                        </thead>
                        <tbody id="tbody-users">
                            
                        </tbody>
                        </table>
            </div>        
            <button type="submit" class="btn btn-primary btn-create-group">Cadastrar</button>
        </form>
    </div>
    
@endsection

resources/views/group/index.blade.php
@extends('layouts.base')

@section('content')

    <div class="title-group col-md-12">
        <h2>Grupos</h2>
    </div>
    @if(isset($groups) && $groups->isNotEmpty())
    @foreach($groups as $group)
    <div class="col-md-2">
        <a href="{{route('groups.show',['id'=>$group->id])}}">
            <i class="icon-group fas fa-users"></i>
            <p>{{$group->name}}</p>
        </a>       
    </div>
    @endforeach  
    @else
    <div class="well text-center center col-md-12 col-xs-12">
        <h3>Nenhum grupo cadastrado no momento!</h3>
    </div> 
    @endif
    <div class="col-md-12">
        <a href="{{route('groups.create')}}">
            <i class="icon-group-new fas fa-plus-circle"></i>
            <p class="p-group">Adicionar Grupo</p>
        </a>       
    </div> 


@endsection

resources/views/group/show.blade.php
@extends('layouts.base')

@section('content')

    
    <div class="title-group col-md-12">
        <h2>Editar Grupo</h2>
    </div>
    @if(isset($group))
    <div class="col-md-12 col-xs-12 form-center">   
        <form action="">
            @csrf
            <input type="hidden" id="groupId" value="{{$group->id}}">
            <div class="form-group col-xs-12 col-md-12">
                <label for="groupName">Nome</label>
                <input name="name" value="{{$group->name}}" type="text" class="form-control" id="groupName" aria-describedby="emailHelp" placeholder="Digite o nome do grupo">
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="searchFor">Pesquisar por</label>
                    <select class="form-control" id="searchFor">
                        <option value="email">E-mail</option>
                        <option value="nome">Nome</option>
                    </select>   
                </div>
                <div class="form-group col-md-6">
                        <label for="inviteSomeone">Convidar Participantes</label>
                        <input id="searchUser" type="text" class="form-control" id="inviteSomeone" placeholder="Pesquisar...">        
                </div>
                <div class="form-group col-md-2">
                    <label for="btn-search"></label>
                    <button type="button" id="btn-search" class="btn form-control" onclick="searchUsersEdit({{$group->id}})">Buscar</button>
                </div>
            </div>
            <div>
            <div>
                <table class="table table-striped">
                        <thead>
                            <tr>
                            <th scope="col">Nome</th>
                            <th scope="col">E-mail</th>
                            <th scope="col">Ação</th>
                            </tr>
                        </thead>
                        <tbody id="tbody-users">
                            
                        </tbody>
                        </table>
            </div>
            <div class="row col-md-12">
                <div class="col-md-4">        
                    <a href="{{route('groups.index')}}" class="btn btn-info btn-create-group">Cancelar</a>            
                </div>
                <div class="col-md-4">
                    <button type="button" onclick="editGroup({{$group->id}})" class="btn btn-primary btn-create-group">Salvar</button>
                </div>
                <div class="col-md-4">
                    <button type="button" onclick="deleteGroup({{$group->id}})" class="btn btn-danger btn-create-group">Excluir</button>
                </div>    
            </div>
        </form>
    </div>
    @else
    <div class="well text-center center col-md-12 col-xs-12">
        <h3>Grupo não encontrado para a edição.</h3>
    </div>
    @endif
@endsection